security:
  oauth2:
    client:
      registration:
        naver:
          client-id: GmAUR9VhV3bsYbQ78dN7
          client-secret: M2nL3EVCil
          redirect-uri: http://localhost:8080/callback
          authorization_grant_type: authorization_code

      provider:
        naver:
          authorization_uri: https://nid.naver.com/oauth2.0/authorize
          token_uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user_name_attribute: response